#!/bin/bash

# lsd-base2
# Copyright (C) 2013 -- M E Leypold

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. mypath.shlib "$0"
. profile-tools.shlib
begin_profile
{
    if ls -1 ~/.scripts/[1-9]*/. 2>/dev/null 1>&2 ; then
	for TEMP_PROFILE in $(find  ~/.scripts/[1-9]*/. -maxdepth 1 -name 'Profile' | sed 's|/[.]/|/|g' | sort ); do 
            eval "$($TEMP_PROFILE -sub)"; 
	done
    fi
}
end_profile

